name: Debug Script

on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - run: pip install keyboard && python test.py > test.txt
      - run: python test.py > test2.txt
      - name: upload res
        uses: actions/upload-artifact@v3.0.0
        with:
          name: test.txt
          path: test.txt
