name: Debug Script

on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - run: pip install keyboard && python test.py
      - run: python test.py
