name: Debug Script

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
     container:
      image: python:3.12.0a2-alpine3.16
      options: --privileged
    steps:
      - uses: actions/checkout@v2
      - run: pip install keyboard
      - run: python test.py
